name: 🚀 deploy

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      library:
        required: true
        type: string
  push:
    branches:
      - main

jobs:
  deploy_trunk:
    uses: libhal/libhal/.github/workflows/deploy.yml@main
    with:
      library: libmpu
    secrets: inherit